[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#334155"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"

